=== Xm798/Genshin-Dailynote-Reminder/alert/config_data/json_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalProperties": true,
  "description": "Genshin Alert Helper 配置文件",
  "properties": {
    "UID": {
      "title": "原神UID",
      "type": "string",
      "pattern": "\\d{9}"
    },
    "NAME": {
      "description": "账号别名",
      "title": "账号别名",
      "type": "string"
    },
    "ALERT_SUCCESS_SLEEP_TIME": {
      "default": 1800,
      "description": "为避免频繁推送扰民可以设置长点（单位：秒）",
      "title": "提示成功后的休眠时间",
      "type": "integer"
    },
    "COOKIE": {
      "title": "米游社 Cookie",
      "type": "string"
    },
    "COOL_PUSH_MODE": {
      "default": "psend",
      "description": "支持\"send\",\"psend\",\"group\",\"pgroup\"。",
      "examples": [
        "send",
        "psend",
        "group",
        "pgroup"
      ],
      "title": "酷推发送模式",
      "type": "string",
      "pattern": "send|psend|group|pgroup"
    },
    "COOL_PUSH_SENDID": {
      "description": "发送模式为send/psend时为QQ号，发送模式为group/pgroup时为群号。",
      "title": "酷推发送对象",
      "type": "string"
    },
    "COOL_PUSH_SKEY": {
      "title": "酷推SKEY",
      "type": "string"
    },
    "DD_BOT_SECRET": {
      "description": "可选项",
      "title": "钉钉机器人加签密钥",
      "type": "string"
    },
    "DD_BOT_TOKEN": {
      "title": "钉钉机器人Token",
      "type": "string"
    },
    "DISCORD_WEBHOOK": {
      "title": "DISCORD_WEBHOOK",
      "type": "string"
    },
    "IGOT_KEY": {
      "title": "IGOT_KEY",
      "type": "string"
    },
    "INCOMPLETE_ALERT": {
      "default": "213030",
      "description": "在这个时间，如果每日委托未完成，进行提示。\"213030\"，即21:30:30。",
      "title": "每日委托未完成提醒时间",
      "type": "string",
      "pattern": "([0-1][0-9]|2[0-3])([0-5][0-9])([0-5][0-9])"
    },
    "SLEEP_START_TIME": {
      "default": "230000",
      "description": "休眠状态开始时间，\"230000\"，即23:00:00。",
      "title": "休眠状态开始时间",
      "type": "string",
      "pattern": "([0-1][0-9]|2[0-3])([0-5][0-9])([0-5][0-9])"
    },
    "SLEEP_END_TIME": {
      "default": "080000",
      "description": "休眠状态结束时间，\"080000\"，即08:00:00。",
      "title": "休眠状态结束时间",
      "type": "string",
      "pattern": "([0-1][0-9]|2[0-3])([0-5][0-9])([0-5][0-9])"
    },
    "PUSH_PLUS_TOKEN": {
      "title": "Pushplus Token",
      "type": "string"
    },
    "PUSH_PLUS_USER": {
      "description": "Pushplus群发模式下的群组ID，一对一推送无需此字段",
      "title": "Pushplus 发送对象",
      "type": "string"
    },
    "QMSG_KEY": {
      "title": "QMSG的KEY",
      "type": "string"
    },
    "RECEIVE_BOSS_COUNT": {
      "description": "ON or OFF",
      "examples": [
        "ON",
        "OFF"
      ],
      "title": "是否接收本周boss树脂减半剩余次数",
      "type": "string",
      "pattern": "ON|OFF"
    },
    "RECEIVE_RESIN_DATA": {
      "description": "ON or OFF",
      "examples": [
        "ON",
        "OFF"
      ],
      "title": "是否接收树脂溢出提示",
      "type": "string",
      "pattern": "ON|OFF"
    },
    "RECEIVE_TASK_NUM": {
      "description": "ON or OFF",
      "examples": [
        "ON",
        "OFF"
      ],
      "title": "是否接收每日委托提示",
      "type": "string",
      "pattern": "ON|OFF"
    },
    "RESIN_ALERT_NUM": {
      "default": 140,
      "title": "树脂达到多少时进行提示",
      "type": "integer"
    },
    "REVEIVE_EXPEDITION_NUM": {
      "description": "ON or OFF",
      "examples": [
        "ON",
        "OFF"
      ],
      "title": "是否接收探索派遣信息",
      "type": "string",
      "pattern": "ON|OFF"
    },
    "EXPEDITION_COMPLETE_ALERT": {
      "description": "ON or OFF",
      "examples": [
        "ON",
        "OFF"
      ],
      "title": "是否接收探索派遣完成提醒",
      "type": "string",
      "pattern": "ON|OFF"
    },
    "SCTKEY": {
      "title": "ServerChan KEY",
      "type": "string"
    },
    "BARK_KEY": {
      "title": "BARK App Key",
      "type": "string"
    },
    "BARK_GROUP": {
      "description": "不填则使用默认分组",
      "title": "自定义 BARK 消息分组",
      "type": "string"
    },
    "BARK_URL": {
      "default": "https://api.day.app/",
      "description": "BARK 服务器，默认为https://api.day.app/",
      "title": "BARK 服务器",
      "type": "string"
    },
    "BARK_ICON": {
      "description": "需要填写URL，不填则不使用自定义图标",
      "default": "https://ae03.alicdn.com/kf/Hca199ca287ee4ee8aa4c8004db6de367o.png",
      "title": "自定义 BARK 通知图标",
      "type": "string"
    },
    "BARK_ARCHIVE": {
      "description": "1 为保存，0为不保存，不填则使用默认规则",
      "title": "设置 BARK 是否保存消息",
      "type": "string",
      "examples": [
        "1",
        "0"
      ]
    },
    "BARK_LEVEL":{
      "description": "active：不设置时的默认值，系统会立即亮屏显示通知；timeSensitive：时效性通知，可在专注状态下显示通知；passive：仅将通知添加到通知列表，不会亮屏提醒",
      "title": "BARK 时效性通知",
      "type": "string",
      "examples": ["active","timeSensitive","passive"],
      "pattern": "active|timeSensitive|passive"
    },
    "SLEEP_TIME": {
      "default": 900,
      "description": "为避免被封ip，建议稍微长点（单位：秒），默认15分钟检查一次",
      "title": "程序每轮执行的休眠时间",
      "type": "integer"
    },
    "TG_BOT_API": {
      "default": "api.telegram.org",
      "description": "国内可自行搭建反代",
      "examples": [
        "api.telegram.org",
        "tgbotapi.xm.mk"
      ],
      "title": "Telegram BOT API地址",
      "type": "string"
    },
    "TG_BOT_TOKEN": {
      "title": "Telegram Bot Token",
      "type": "string"
    },
    "TG_USER_ID": {
      "title": "Telegram 接收用户的 userid",
      "type": "string"
    },
    "WW_APP_AGENTID": {
      "title": "企业微信应用Id",
      "type": "string"
    },
    "WW_APP_SECRET": {
      "title": "企业微信Secret",
      "type": "string"
    },
    "WW_APP_USERID": {
      "title": "企业微信接收消息的用户id",
      "type": "string"
    },
    "WW_BOT_KEY": {
      "title": "企业微信机器人Key",
      "type": "string"
    },
    "WW_ID": {
      "title": "企业微信id",
      "type": "string"
    },
    "PUSHDEER_KEY": {
      "title": "pushdeer 的推送 key",
      "type": "string"
    },
    "CQHTTP_URL": {
      "description": "格式：协议头://IP 或域名:端口号",
      "title": " cqhttp 的 API 地址",
      "type": "string"
    },
    "CQHTTP_MESSAGE_TYPE": {
      "description": "private为私聊发送，group为群聊发送",
      "examples": [
        "private",
        "group"
      ],
      "title": "cqhttp消息发送模式",
      "type": "string",
      "pattern": "private|group"
    },
    "CQHTTP_SEND_ID": {
      "title": "推送的对象(QQ号码/群号码)",
      "type": "string"
    },
    "CQHTTP_TOKEN": {
      "title": "cqhttp的access_token，未设置则不填",
      "type": "string"
    },
    "RECEIVE_HOMECOIN_ALERT": {
      "default": "ON",
      "description": "ON or OFF",
      "title": "是否接收洞天宝钱溢出提醒",
      "type": "string",
      "pattern": "ON|OFF",
      "examples": [
        "ON",
        "OFF"
      ]
    },
    "RUN_ENV": {
      "default": "local",
      "description": "cloud|local",
      "title": "运行环境，国内云服务器使用'cloud'，本地运行使用'local'",
      "type": "string",
      "pattern": "cloud|local"
    }
  },
  "required": [
    "UID",
    "COOKIE",
    "RESIN_ALERT_NUM",
    "RECEIVE_RESIN_DATA",
    "RECEIVE_BOSS_COUNT",
    "RECEIVE_TASK_NUM",
    "REVEIVE_EXPEDITION_NUM",
    "EXPEDITION_COMPLETE_ALERT",
    "INCOMPLETE_ALERT",
    "SLEEP_TIME",
    "ALERT_SUCCESS_SLEEP_TIME",
    "RECEIVE_HOMECOIN_ALERT"
  ],
  "type": "object"
}

=== Xm798/Genshin-Dailynote-Reminder/alert/config_data/config.example.json
{
  "$schema": "https://file-1257193553.cos.ap-shanghai.myqcloud.com/GenshinAlert/GAH_schema_v1.3.2.json",
  "RUN_ENV": "local",
  "UID": "",
  "COOKIE": "",
  "NAME": "",

  "RESIN_ALERT_NUM": 140,
  "RECEIVE_RESIN_DATA": "ON",
  "RECEIVE_BOSS_COUNT": "ON",
  "RECEIVE_TASK_NUM": "ON",
  "RECEIVE_HOMECOIN_ALERT":"ON",
  "REVEIVE_EXPEDITION_NUM": "ON",
  "INCOMPLETE_ALERT": "213030",
  "EXPEDITION_COMPLETE_ALERT": "ON",
  "SLEEP_TIME": 900,
  "ALERT_SUCCESS_SLEEP_TIME": 1800,
  "SLEEP_START_TIME": "",
  "SLEEP_END_TIME": "",

  "WW_ID": "",
  "WW_APP_SECRET": "",
  "WW_APP_USERID": "",
  "WW_APP_AGENTID": "",
  "WW_BOT_KEY": "",
  "BARK_URL": "https://api.day.app/",
  "BARK_KEY": "",
  "BARK_GROUP": "",
  "BARK_ICON": "https://ae03.alicdn.com/kf/Hca199ca287ee4ee8aa4c8004db6de367o.png",
  "BARK_ARCHIVE": "",
  "BARK_LEVEL": "",
  "TG_BOT_API": "api.telegram.org",
  "TG_BOT_TOKEN": "",
  "TG_USER_ID": "",
  "PUSHDEER_KEY":"",
  "CQHTTP_URL": "",
  "CQHTTP_MESSAGE_TYPE": "private",
  "CQHTTP_SEND_ID": "",
  "CQHTTP_TOKEN": "",
  "DD_BOT_TOKEN": "",
  "DD_BOT_SECRET": "",
  "SCTKEY": "",
  "PUSH_PLUS_TOKEN": "",
  "PUSH_PLUS_USER": "",
  "COOL_PUSH_SKEY": "",
  "COOL_PUSH_MODE": "psend",
  "COOL_PUSH_SENDID": "",
  "QMSG_KEY": "",
  "DISCORD_WEBHOOK": "",
  "IGOT_KEY": ""
}
